create extension if not exists "vector" with schema "public" version '0.8.0';

create table "public"."code_embeddings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "content" text,
    "embedding" vector(1536),
    "file_path" text,
    "symbol_type" text,
    "symbol_name" text,
    "start_line" integer,
    "end_line" integer
);


CREATE UNIQUE INDEX code_embeddings_pkey ON public.code_embeddings USING btree (id);

alter table "public"."code_embeddings" add constraint "code_embeddings_pkey" PRIMARY KEY using index "code_embeddings_pkey";

grant delete on table "public"."code_embeddings" to "anon";

grant insert on table "public"."code_embeddings" to "anon";

grant references on table "public"."code_embeddings" to "anon";

grant select on table "public"."code_embeddings" to "anon";

grant trigger on table "public"."code_embeddings" to "anon";

grant truncate on table "public"."code_embeddings" to "anon";

grant update on table "public"."code_embeddings" to "anon";

grant delete on table "public"."code_embeddings" to "authenticated";

grant insert on table "public"."code_embeddings" to "authenticated";

grant references on table "public"."code_embeddings" to "authenticated";

grant select on table "public"."code_embeddings" to "authenticated";

grant trigger on table "public"."code_embeddings" to "authenticated";

grant truncate on table "public"."code_embeddings" to "authenticated";

grant update on table "public"."code_embeddings" to "authenticated";

grant delete on table "public"."code_embeddings" to "service_role";

grant insert on table "public"."code_embeddings" to "service_role";

grant references on table "public"."code_embeddings" to "service_role";

grant select on table "public"."code_embeddings" to "service_role";

grant trigger on table "public"."code_embeddings" to "service_role";

grant truncate on table "public"."code_embeddings" to "service_role";

grant update on table "public"."code_embeddings" to "service_role";


